version: '3'

services:
  trophies:
    image: ghcr.io/lukecarr/trophies:latest
    restart: unless-stopped
    expose:
      - '3000'
    volumes:
      - trophies_data:/data
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from ${DOMAIN} --to trophies:3000

volumes:
  trophies_data: {}
  caddy_data: {}
  caddy_config: {}