image: gitpod/workspace-full

tasks:
  - name: Go dependencies
    init: >
      go mod download &&
      gp sync-done go-deps
  
  - name: Node.js dependencies
    init: >
      cd frontend &&
      pnpm install --frozen-lockfile &&
      gp sync-done nodejs-deps

  - name: Run application
    init: >
      gp sync-await go-deps &&
      gp sync-await nodejs-deps
    command: make run
    env:
      DSN: /workspace/trophies/trophies.db

ports:
  - name: HTTP
    port: 3000
    onOpen: open-browser
