image: gitpod/workspace-full

tasks:
  - name: Run application
    init: go mod download && cd frontend && pnpm install --frozen-lockfile
    command: make run
    env:
      DSN: /workspace/trophies/trophies.db

ports:
  - name: HTTP
    port: 3000
    onOpen: ignore
