before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: trophies
    ldflags:
      - -s -w -X github.com/lukecarr/trophies/internal/info.Version={{.Tag}} -X github.com/lukecarr/trophies/internal/info.Commit={{.FullCommit}} -X github.com/lukecarr/trophies/internal/info.Date={{.Date}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - freebsd_amd64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_amd64

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: lukecarr
    name: trophies
