version: '3'

services:
  trophies:
    image: ghcr.io/lukecarr/trophies:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - sqlite_data:/data
    environment:
      - DSN=/data/trophies.db

volumes:
  sqlite_data: {}
