name: Format

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - name: Install dprint
        shell: bash
        run: curl -fsSL https://dprint.dev/install.sh | sh

      - name: Check formatting
        shell: bash
        run: ~/.dprint/bin/dprint check
